# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast computation of \eqn{X ^ T \Omega X} for Generalized Linear Model Solving
#'
#' @param w The vector of weights.
#' @param alpha Vector of indexes representing the start of blocks of the design matrix, as given by \link{block_design}.
#' @param B The matrix \code{X} given in compressed block format, as given by \link{block_design}.
#' @return The matrix \eqn{X^T diag(w) X} where \code{X} is the design matrix and \code{W = diag(w)} is
#' a diagonal matrix of weights.
#' @export
weight_design_band <- function(w, alpha, B) {
    .Call('_aspline_weight_design_band', PACKAGE = 'aspline', w, alpha, B)
}

#' Create the matrix of weights
#'
#' @param w The vector of weights
#' @param diff The order of the differences to be applied to the parameters. Must be a strictly positive integer
#' @return The matrix of weights \eqn{D^T diag(w) D} where
#'  \code{D <- diff(diag(length(w) + diff), differences = diff)}. Only the non-null superdiagonals of
#'  the weight matrixare returned, each column corresponding to a diagonal.
#' @export
band_weight <- function(w, diff) {
    .Call('_aspline_band_weight', PACKAGE = 'aspline', w, diff)
}

