# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create the matrix of weights
#'
#' @param w The vector of weights
#' @param diff The order of the differences to be applied to the parameters. Must be a strictly positive integer
#' @return The matrix of weights \eqn{D^T diag(w) D} where
#'  \code{D <- diff(diag(length(w) + diff), differences = diff)}. Only the non-null superdiagonals of
#'  the weight matrixare returned, each column corresponding to a diagonal.
#' @export
band_weight <- function(w, diff) {
    .Call('_aspline_band_weight', PACKAGE = 'aspline', w, diff)
}

