on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
